// Content is separate from the shared trainer. Index loads it before app.js.
function rs(id, group, context, direct, answers, rule, changes, instruction = "Передай фразу с согласованием времён (backshift).") {
  return { id, ruleKey: id, group, context, direct, answers, rule, changes, instruction };
}

const REPORTED_ITEMS = [
  rs("tense-work", "tense", "Марта рассказывала о своей прежней работе. Ты пересказываешь её слова.", "Marta: ‘I work remotely.’", ["Marta said that she worked remotely.", "Marta said that she works remotely.", "Marta said that I worked remotely.", "Marta told that she worked remotely."], "Present Simple → Past Simple", ["Время: work → worked после said.", "Лицо: I — это Марта, поэтому she."]),
  rs("tense-be", "tense", "Вчера Лео говорил о своей усталости. Сейчас ты рассказываешь об этом.", "Leo: ‘I am exhausted.’", ["Leo said that he was exhausted.", "Leo said that he is exhausted.", "Leo said that I was exhausted.", "Leo said that he had exhausted."], "am/is → was", ["Время: am → was; exhausted остаётся прилагательным.", "Лицо: I → he, потому что речь о Лео."]),
  rs("tense-negative", "tense", "Анна рассказывала о своих прежних привычках.", "Anna: ‘I don't drink coffee.’", ["Anna said that she didn't drink coffee.", "Anna said that she doesn't drink coffee.", "Anna said that she didn't drank coffee.", "Anna said that I didn't drink coffee."], "don't/doesn't → didn't + V", ["Время: don't → didn't.", "После didn't остаётся базовая форма drink, не drank.", "Лицо: I → she."]),
  rs("tense-continuous", "tense", "Вчера Нина описала, чем занималась в тот момент.", "Nina: ‘I am studying.’", ["Nina said that she was studying.", "Nina said that she is studying.", "Nina said that she studied.", "Nina said that I was studying."], "Present Continuous → Past Continuous", ["Время: am studying → was studying; процесс остаётся процессом.", "Лицо: I → she."]),
  rs("tense-past", "tense", "Дэн рассказал о концерте, на котором уже побывал.", "Dan: ‘I loved the concert.’", ["Dan said that he had loved the concert.", "Dan said that he loves the concert.", "Dan said that he has loved the concert.", "Dan said that I had loved the concert."], "Past Simple → Past Perfect", ["Время: loved → had loved при стандартном backshift.", "Лицо: I → he.", "Past Simple иногда сохраняют; здесь условие просит вариант со сдвигом."]),
  rs("tense-perfect", "tense", "Инес рассказывала о своём опыте на тот момент.", "Ines: ‘I have never been to Rome.’", ["Ines said that she had never been to Rome.", "Ines said that she has never been to Rome.", "Ines said that she had never went to Rome.", "Ines said that I had never been to Rome."], "Present Perfect → Past Perfect", ["Время: have been → had been; never остаётся после помощника.", "Лицо: I → she."]),
  rs("tense-past-process", "tense", "Сэм объяснял, чем занимался ещё до разговора.", "Sam: ‘I was working.’", ["Sam said that he had been working.", "Sam said that he is working.", "Sam said that he has been working.", "Sam said that I had been working."], "Past Continuous → Past Perfect Continuous", ["Время: was working → had been working при backshift.", "Лицо: I → he."]),
  rs("tense-past-perfect", "tense", "Лаура говорила, что уже отправила отчёт до другого прошлого события.", "Laura: ‘I had already sent the report.’", ["Laura said that she had already sent the report.", "Laura said that she has already sent the report.", "Laura said that she had had sent the report.", "Laura said that I had already sent the report."], "Past Perfect не сдвигается дальше", ["Время: had sent остаётся had sent. Второй had не добавляем.", "Лицо: I → she."]),

  rs("modal-will", "modal", "Том пообещал помочь тебе. Ты пересказываешь это другому человеку.", "Tom to you: ‘I will help you.’", ["Tom said that he would help me.", "Tom said that he will help me.", "Tom said that I would help you.", "Tom told that he would help me."], "will → would", ["Модальный: will → would.", "Лица: I → he (Том), you → me (ты пересказываешь от своего лица)."]),
  rs("modal-can", "modal", "Сара разрешила тебе остановиться у неё.", "Sara to you: ‘You can stay with me.’", ["Sara said that I could stay with her.", "Sara said that I can stay with her.", "Sara said that you could stay with me.", "Sara said that I could to stay with her."], "can → could", ["Модальный: can → could.", "Лица: you → I, me → her.", "После could — stay без to."]),
  rs("modal-may", "modal", "Алекс говорил о возможном опоздании, не о разрешении.", "Alex: ‘I may arrive late.’", ["Alex said that he might arrive late.", "Alex said that he may arrive late.", "Alex said that I might arrive late.", "Alex said that he might to arrive late."], "may (возможность) → might", ["Модальный: may → might для возможности.", "Лицо: I → he."]),
  rs("modal-must-duty", "modal", "Елена сказала тебе об обязанности; ты пересказываешь прошедшую ситуацию.", "Elena to you: ‘You must pay attention.’", ["Elena told me that I had to pay attention.", "Elena told me that I had to paid attention.", "Elena said me that I had to pay attention.", "Elena told that you had to pay attention."], "must (обязанность) → had to", ["Обязанность в прошлом: must → had to.", "Лицо: you → I; после told назван адресат me.", "После had to остаётся pay."]),
  rs("modal-could", "modal", "Хьюго рассказывал об умении, которое у него было в детстве.", "Hugo: ‘I could swim at five.’", ["Hugo said that he could swim at five.", "Hugo said that he can swim at five.", "Hugo said that he had could swim at five.", "Hugo said that I could swim at five."], "could остаётся could", ["Модальный: could обычно не меняется при пересказе.", "Лицо: I → he."]),
  rs("modal-should", "modal", "Лена посоветовала тебе отдохнуть. Ты рассказываешь об этом.", "Lena to you: ‘You should rest.’", ["Lena told me that I should rest.", "Lena told me that I had to rest.", "Lena told me that I should to rest.", "Lena told that I should rest."], "should остаётся should", ["Совет остаётся советом: should не превращается в had to.", "Лицо: you → I. После told нужен me."]),
  rs("modal-might", "modal", "Эва говорила о возможной задержке.", "Eva: ‘I might be late.’", ["Eva said that she might be late.", "Eva said that she may be late.", "Eva said that she had might be late.", "Eva said that I might be late."], "might остаётся might", ["Модальный: might не сдвигается дальше.", "Лицо: I → she."]),
  rs("modal-must-guess", "modal", "Лена сделала вывод по гудению сервера, а не приказала ему работать.", "Lena: ‘The server must be running.’", ["Lena said that the server must be running.", "Lena said that the server had to run.", "Lena told that the server must be running.", "Lena said that the server must to be running."], "must (вывод) обычно сохраняется", ["Must здесь означает «должно быть», а не обязанность.", "Обычно сохраняем must; had to run поменяло бы смысл на необходимость."], "Передай вывод, сохранив его смысл."),

  rs("reference-owner", "reference", "София говорила о своей собственной квартире.", "Sofia: ‘I like my flat.’", ["Sofia said that she liked her flat.", "Sofia said that she liked my flat.", "Sofia said that I liked her flat.", "Sofia said that she likes her flat."], "I/my → she/her по личности говорящего", ["Время: like → liked.", "I и my относятся к Софии: she и her."]),
  rs("reference-you", "reference", "Павел сказал это тебе. Ты передаёшь его слова от своего лица.", "Pavel to you: ‘Your report is ready.’", ["Pavel told me that my report was ready.", "Pavel told me that your report was ready.", "Pavel told that my report was ready.", "Pavel told me that my report is ready."], "your → my по адресату исходной фразы", ["Your относится к тебе, поэтому в твоём пересказе — my.", "Время: is → was. Told + me."]),
  rs("reference-we", "reference", "Два коллеги говорили о своей команде. Ты не входишь в неё.", "The colleagues: ‘We are proud of our team.’", ["They said that they were proud of their team.", "They said that we were proud of our team.", "They said that they are proud of their team.", "They said that they were proud of your team."], "we/our → they/their, если рассказчик вне группы", ["Говорящие — отдельная группа: we → they, our → their.", "Время: are → were."]),
  rs("reference-tomorrow", "reference", "В понедельник Омар сказал это тебе. Ты пересказываешь в среду.", "Omar: ‘I will call tomorrow.’", ["Omar said that he would call the next day.", "Omar said that he would call tomorrow.", "Omar said that he will call the next day.", "Omar said that he would call the day before."], "tomorrow → the next day при смене дня", ["Время: will → would; I → he.", "Tomorrow означало вторник, а не четверг: the next day — после исходного разговора."]),
  rs("reference-yesterday", "reference", "Во вторник Эмма говорила о понедельнике. Пересказываешь в пятницу.", "Emma: ‘I arrived yesterday.’", ["Emma said that she had arrived the day before.", "Emma said that she had arrived yesterday.", "Emma said that she has arrived the day before.", "Emma said that she had arrived the next day."], "yesterday → the day before при смене дня", ["Время: arrived → had arrived; I → she.", "The day before — день до исходного разговора, то есть понедельник."]),
  rs("reference-now", "reference", "Райан описывал своё состояние вчера. Ты рассказываешь об этом сегодня.", "Ryan: ‘I am busy now.’", ["Ryan said that he was busy then.", "Ryan said that he was busy now.", "Ryan said that he is busy then.", "Ryan said that I was busy then."], "now → then при смене момента", ["Время: am → was; I → he.", "Then указывает на момент исходного разговора."]),
  rs("reference-here", "reference", "Карла сказала это в Бильбао. Теперь ты пересказываешь её слова из Мадрида.", "Carla: ‘I work here.’", ["Carla said that she worked there.", "Carla said that she worked here.", "Carla said that she works there.", "Carla said that I worked there."], "here → there при смене места", ["Время: work → worked; I → she.", "Место рассказчика изменилось: here → there (Бильбао)."]),
  rs("reference-today", "reference", "В понедельник Бен сообщил о свободном дне. Пересказываешь в четверг.", "Ben: ‘I am free today.’", ["Ben said that he was free that day.", "Ben said that he was free today.", "Ben said that he is free that day.", "Ben said that I was free that day."], "today → that day при смене дня", ["Время: am → was; I → he.", "That day — понедельник, а не сегодняшний четверг."]),

  rs("structure-told", "structure", "Луис сообщил тебе, что устал.", "Luis to you: ‘I am tired.’", ["Luis told me that he was tired.", "Luis told that he was tired.", "Luis said me that he was tired.", "Luis told to me that he was tired."], "told + адресат + (that) + предложение", ["В этой конструкции после told нужен адресат: me.", "Время: am → was; I → he."], "Выбери правильную конструкцию с told и backshift."),
  rs("structure-said", "structure", "Ты просто сообщаешь, что произнесла Рита, без адресата.", "Rita: ‘I am ready.’", ["Rita said that she was ready.", "Rita said me that she was ready.", "Rita told that she was ready.", "Rita said that was she ready."], "said + (that) + предложение", ["После said можно сразу передать содержание; said me неправильно.", "Время: am → was; порядок слов утверждения: she was."], "Выбери правильный пересказ с said и backshift."),
  rs("structure-said-to", "structure", "Мила сказала это тебе. Нужно сохранить said и назвать адресата.", "Mila to you: ‘I am leaving.’", ["Mila said to me that she was leaving.", "Mila said me that she was leaving.", "Mila said to me that I was leaving.", "Mila said to me that she is leaving."], "said to + адресат (не said me)", ["Say допускает адресата с to: said to me.", "Время: am leaving → was leaving; I → she."], "Сохрани said, укажи адресата и используй backshift."),
  rs("structure-that", "structure", "Люк сказал: «Я устал». Начни с Luke said и опусти that.", "Luke: ‘I am tired.’", ["Luke said he was tired.", "Luke said was he tired.", "Luke told he was tired.", "Luke said he tired."], "that в пересказе утверждения можно опустить", ["Luke said (that) he was tired — оба варианта допустимы.", "Условие просит убрать that, но сохранить he was и обычный порядок слов."], "Передай с backshift без that."),
  rs("structure-says", "structure", "Джо говорит это сейчас о своей текущей работе.", "Joe: ‘I work remotely.’", ["Joe says that he works remotely.", "Joe says that I work remotely.", "Joe says that he work remotely.", "Joe says me that he works remotely."], "после says сдвиг не нужен сам по себе", ["Says — настоящее: для текущего факта сохраняем Present Simple.", "I → he, поэтому work → works по лицу, а не по времени."], "Начни с Joe says и сохрани настоящее время."),
  rs("structure-still-true", "structure", "Мария только что сказала это; она всё ещё живёт в Бильбао. Подчеркни актуальность факта.", "Maria: ‘I live in Bilbao.’", ["Maria said that she lives in Bilbao.", "Maria said that she had lived in Bilbao.", "Maria said that I live in Bilbao.", "Maria told that she lives in Bilbao."], "актуальный факт можно передать без backshift", ["Lives подчёркивает, что факт остаётся верным.", "Lived тоже бывает допустимо, но в этом задании просим сохранить актуальное настоящее."], "Сохрани настоящее время для по-прежнему верного факта."),
  rs("structure-general-truth", "structure", "Учитель сообщил общеизвестный факт. Сохрани его как общую истину.", "The teacher: ‘The Earth orbits the Sun.’", ["The teacher said that the Earth orbits the Sun.", "The teacher said that the Earth orbit the Sun.", "The teacher told that the Earth orbits the Sun.", "The teacher said that does the Earth orbit the Sun."], "общую истину можно оставить в настоящем", ["Общая истина: orbits можно не сдвигать.", "Порядок слов обычный: the Earth orbits, без do/does."], "Выбери пересказ без backshift с обычным порядком слов."),
  rs("structure-same-context", "structure", "Ана только что сказала это в кафе. Ты всё ещё там и пересказываешь в тот же день.", "Ana: ‘I am working here today.’", ["Ana said that she is working here today.", "Ana said that I am working here today.", "Ana told that she is working here today.", "Ana said she working here today."], "here/today сохраняются, если место и день те же", ["Ситуация продолжается: по условию сохраняем is working.", "Место и день те же: here и today по-прежнему точны.", "I → she. В другом контексте возможны there и that day."], "Сохрани актуальное время, место и день без backshift."),
];

// Reuse the grammar rule, not the sentence: every variant has its own context,
// full answers and explanation. ruleKey keeps recognition distractors unambiguous.
function rsVariant(baseId, id, context, direct, answers, changes, instruction) {
  const base = REPORTED_ITEMS.find(item => item.id === baseId);
  if (!base) throw new Error(`Unknown reported-speech rule: ${baseId}`);
  return { ...base, id, context, direct, answers, changes, instruction: instruction || base.instruction };
}

REPORTED_ITEMS.push(
  rsVariant("tense-work", "tense-cycle", "Эрик рассказывал, как добирался до своего прежнего офиса.", "Eric: ‘I cycle to the office.’", ["Eric said that he cycled to the office.", "Eric said that he cycles to the office.", "Eric said that I cycled to the office.", "Eric told that he cycled to the office."], ["Present Simple → Past Simple: cycle → cycled.", "I относится к Эрику: в пересказе he."]),
  rsVariant("tense-work", "tense-clients", "Паула описала свой прежний рабочий распорядок.", "Paula: ‘I meet clients on Mondays.’", ["Paula said that she met clients on Mondays.", "Paula said that she meets clients on Mondays.", "Paula said that she meeted clients on Mondays.", "Paula said that I met clients on Mondays."], ["Meet — неправильный глагол: meet → met, не meeted.", "Привычка передаётся через Past Simple; I → she."]),
  rsVariant("tense-be", "tense-hungry", "Вчера Оскар пожаловался, что голоден. Ты рассказываешь о вчерашнем разговоре.", "Oscar: ‘I am hungry.’", ["Oscar said that he was hungry.", "Oscar said that he is hungry.", "Oscar said that I was hungry.", "Oscar said that he did hungry."], ["Am → was при сдвиге в прошлое.", "Hungry — прилагательное: нужен be, а не do; I → he."]),
  rsVariant("tense-be", "tense-server-offline", "Администратор рассказал о состоянии сервера в момент сбоя.", "The administrator: ‘The server is offline.’", ["The administrator said that the server was offline.", "The administrator said that the server is offline.", "The administrator said that the server were offline.", "The administrator told that the server was offline."], ["Is → was: server в единственном числе.", "Offline описывает состояние; форму did не добавляем."]),
  rsVariant("tense-negative", "tense-weekends", "Марк рассказывал о графике своей прежней работы.", "Mark: ‘I don't work at weekends.’", ["Mark said that he didn't work at weekends.", "Mark said that he doesn't work at weekends.", "Mark said that he didn't worked at weekends.", "Mark said that I didn't work at weekends."], ["Don't → didn't при backshift.", "После didn't нужна базовая work; I → he."]),
  rsVariant("tense-negative", "tense-app-offline", "Тестировщик описывал ограничение старой версии приложения.", "The tester: ‘The app doesn't work offline.’", ["The tester said that the app didn't work offline.", "The tester said that the app doesn't work offline.", "The tester said that the app didn't works offline.", "The tester said that the app hadn't work offline."], ["Doesn't → didn't: отрицательный Present Simple становится Past Simple.", "Окончание -s не переходит к work: после didn't стоит V."]),
  rsVariant("tense-continuous", "tense-waiting", "Вчера Ада сообщила, что делает прямо во время звонка.", "Ada: ‘I am waiting for the bus.’", ["Ada said that she was waiting for the bus.", "Ada said that she is waiting for the bus.", "Ada said that she waited for the bus.", "Ada said that I was waiting for the bus."], ["Am waiting → was waiting: сохраняем процесс, сдвигаем помощник.", "I → she, поскольку говорила Ада."]),
  rsVariant("tense-continuous", "tense-uploading", "Разработчики сообщили, что загрузка шла в момент разговора. Ты не входишь в их команду.", "The developers: ‘We are uploading the files.’", ["The developers said that they were uploading the files.", "The developers said that they are uploading the files.", "The developers said that they was uploading the files.", "The developers said that we were uploading the files."], ["Are uploading → were uploading: Past Continuous.", "We → they, потому что ты пересказываешь слова другой команды."]),
  rsVariant("tense-past", "tense-lost-ticket", "Хлоя рассказала, что потеряла билет до вашего разговора.", "Chloe: ‘I lost my ticket.’", ["Chloe said that she had lost her ticket.", "Chloe said that she has lost her ticket.", "Chloe said that she had lose her ticket.", "Chloe said that I had lost my ticket."], ["Lost → had lost: Past Simple → Past Perfect по условию backshift.", "После had нужна V3 lost; I/my → she/her."]),
  rsVariant("tense-past", "tense-bought-desk", "Бруно рассказал о покупке, которую уже совершил.", "Bruno: ‘I bought a new desk.’", ["Bruno said that he had bought a new desk.", "Bruno said that he has bought a new desk.", "Bruno said that he had buy a new desk.", "Bruno said that I had bought a new desk."], ["Bought → had bought при стандартном сдвиге.", "Buy — bought — bought: после had нужна третья форма; I → he."]),
  rsVariant("tense-perfect", "tense-finished-design", "Ирис сообщила о готовом результате работы к моменту разговора.", "Iris: ‘I have finished the design.’", ["Iris said that she had finished the design.", "Iris said that she has finished the design.", "Iris said that she had finish the design.", "Iris said that I had finished the design."], ["Have finished → had finished: Present Perfect → Past Perfect.", "Меняется помощник have, а finished остаётся V3; I → she."]),
  rsVariant("tense-perfect", "tense-never-flown", "Джек рассказывал о своём жизненном опыте на тот момент.", "Jack: ‘I have never flown before.’", ["Jack said that he had never flown before.", "Jack said that he has never flown before.", "Jack said that he had never flew before.", "Jack said that I had never flown before."], ["Have flown → had flown; fly — flew — flown.", "Never стоит после had; I → he."]),
  rsVariant("tense-past-process", "tense-cooking", "Лия объяснила, чем занималась до разговора с тобой.", "Lia: ‘I was cooking dinner.’", ["Lia said that she had been cooking dinner.", "Lia said that she has been cooking dinner.", "Lia said that she had cooking dinner.", "Lia said that I had been cooking dinner."], ["Was cooking → had been cooking при полном backshift.", "В Past Perfect Continuous нужны had + been + V-ing; I → she."]),
  rsVariant("tense-past-process", "tense-testing", "Инженеры описали процесс, который шёл раньше вашего разговора.", "The engineers: ‘We were testing the update.’", ["The engineers said that they had been testing the update.", "The engineers said that they have been testing the update.", "The engineers said that they had been tested the update.", "The engineers said that we had been testing the update."], ["Were testing → had been testing: процесс до прошлого момента.", "Testing остаётся V-ing, не tested; we → they."]),
  rsVariant("tense-past-perfect", "tense-already-left", "Роза сказала, что уже ушла до прихода курьера.", "Rosa: ‘I had already left before the courier arrived.’", ["Rosa said that she had already left before the courier arrived.", "Rosa said that she has already left before the courier arrived.", "Rosa said that she had had left before the courier arrived.", "Rosa said that I had already left before the courier arrived."], ["Had left уже Past Perfect: дальше его не сдвигаем.", "I → she. Before ясно задаёт порядок событий; arrived можно сохранить."]),
  rsVariant("tense-past-perfect", "tense-booked-room", "Виктор объяснял, что забронировал комнату ещё до изменения планов.", "Victor: ‘I had booked a room.’", ["Victor said that he had booked a room.", "Victor said that he has booked a room.", "Victor said that he had had booked a room.", "Victor said that I had booked a room."], ["Had booked остаётся had booked: Past Perfect не уходит ещё дальше.", "I относится к Виктору, поэтому he."]),
);

REPORTED_ITEMS.push(
  rsVariant("modal-will", "modal-send-link", "Итан пообещал прислать тебе ссылку. Ты пересказываешь его обещание.", "Ethan to you: ‘I will send you the link.’", ["Ethan said that he would send me the link.", "Ethan said that he will send me the link.", "Ethan said that he would sent me the link.", "Ethan said that I would send you the link."], ["Will → would при backshift.", "После would — send, не sent; I → he, you → me."]),
  rsVariant("modal-will", "modal-wont-attend", "Кейт сообщила, что не придёт на встречу. Ты пересказываешь это после разговора.", "Kate: ‘I won't attend the meeting.’", ["Kate said that she wouldn't attend the meeting.", "Kate said that she won't attend the meeting.", "Kate said that she didn't would attend the meeting.", "Kate said that I wouldn't attend the meeting."], ["Won't = will not → wouldn't = would not.", "Отрицание уже внутри wouldn't; did не нужен; I → she."]),
  rsVariant("modal-can", "modal-can-drive", "Тео рассказывал о своём умении водить машину.", "Theo: ‘I can drive a van.’", ["Theo said that he could drive a van.", "Theo said that he can drive a van.", "Theo said that he could drove a van.", "Theo said that I could drive a van."], ["Can → could: способность в пересказе со сдвигом.", "После could базовая drive, не drove; I → he."]),
  rsVariant("modal-can", "modal-cant-open", "Майя сообщила, что в момент разговора не могла открыть файл.", "Maya: ‘I can't open the attachment.’", ["Maya said that she couldn't open the attachment.", "Maya said that she can't open the attachment.", "Maya said that she couldn't to open the attachment.", "Maya said that I couldn't open the attachment."], ["Can't → couldn't при backshift.", "Open остаётся без to после модального; I → she."]),
  rsVariant("modal-may", "modal-may-rain", "Нора предположила, что возможен дождь. Она не давала разрешение.", "Nora: ‘It may rain.’", ["Nora said that it might rain.", "Nora said that it may rain.", "Nora said that it might rains.", "Nora told that it might rain."], ["May выражает возможность: may → might.", "После might глагол rain без -s; безличное it сохраняется."]),
  rsVariant("modal-may", "modal-may-not-finish", "Феликс предупредил, что, возможно, не успеет закончить задачу.", "Felix: ‘I may not finish the task.’", ["Felix said that he might not finish the task.", "Felix said that he may not finish the task.", "Felix said that he didn't might finish the task.", "Felix said that I might not finish the task."], ["May not → might not: сохраняем неуверенность, а не делаем запрет.", "Not ставится после might, без did; I → he."]),
  rsVariant("modal-must-duty", "modal-must-wear", "Руководитель сказал тебе об обязательной каске. Ты пересказываешь правило той прошлой смены.", "The supervisor to you: ‘You must wear a helmet.’", ["The supervisor told me that I had to wear a helmet.", "The supervisor told me that I had to wore a helmet.", "The supervisor said me that I had to wear a helmet.", "The supervisor told that I had to wear a helmet."], ["Обязанность: must → had to в пересказе прошлой ситуации.", "You → I, адресат после told — me; после to нужна wear."]),
  rsVariant("modal-must-duty", "modal-must-pay", "Лола рассказала об обязанности заплатить до истёкшего срока.", "Lola: ‘I must pay the invoice.’", ["Lola said that she had to pay the invoice.", "Lola said that she had to paid the invoice.", "Lola said that she had pay the invoice.", "Lola told that she had to pay the invoice."], ["Must в значении обязанности обычно становится had to.", "Цепочка had to + pay, не had pay; I → she."]),
  rsVariant("modal-could", "modal-could-read", "Айви рассказывала, что умела читать в детстве.", "Ivy: ‘I could read at four.’", ["Ivy said that she could read at four.", "Ivy said that she can read at four.", "Ivy said that she had could read at four.", "Ivy said that I could read at four."], ["Could для прошлого умения не сдвигаем ещё раз.", "Не добавляем had к could; I → she."]),
  rsVariant("modal-could", "modal-couldnt-find", "Ноа рассказал о неудачной попытке найти ключи до разговора.", "Noah: ‘I couldn't find my keys.’", ["Noah said that he couldn't find his keys.", "Noah said that he can't find his keys.", "Noah said that he had couldn't find his keys.", "Noah said that I couldn't find my keys."], ["Couldn't обычно сохраняется при пересказе.", "I/my → he/his; find остаётся базовой формой после could."]),
  rsVariant("modal-should", "modal-should-backup", "Оливия посоветовала тебе сделать копию файлов.", "Olivia to you: ‘You should back up your files.’", ["Olivia told me that I should back up my files.", "Olivia told me that I had to back up my files.", "Olivia told me that I should to back up my files.", "Olivia told that I should back up my files."], ["Совет с should остаётся should, не превращается в обязанность had to.", "You/your → I/my; после should — back up без to."]),
  rsVariant("modal-should", "modal-shouldnt-skip", "Диетолог посоветовал тебе не пропускать обед.", "The dietitian to you: ‘You shouldn't skip lunch.’", ["The dietitian told me that I shouldn't skip lunch.", "The dietitian told me that I didn't should skip lunch.", "The dietitian told me that I shouldn't to skip lunch.", "The dietitian said me that I shouldn't skip lunch."], ["Shouldn't остаётся shouldn't; do/did не используются.", "После told назван адресат me, you → I; skip без to."]),
  rsVariant("modal-might", "modal-might-change", "Бен допускал изменение плана, но ничего не обещал.", "Ben: ‘The plan might change.’", ["Ben said that the plan might change.", "Ben said that the plan may change.", "Ben said that the plan had might change.", "Ben told that the plan might change."], ["Might уже не требует дальнейшего backshift.", "После might — change; had might не существует."]),
  rsVariant("modal-might", "modal-might-not-work", "Зои сомневалась, что её идея сработает.", "Zoe: ‘My idea might not work.’", ["Zoe said that her idea might not work.", "Zoe said that her idea may not work.", "Zoe said that her idea didn't might work.", "Zoe said that my idea might not work."], ["Might not сохраняется целиком.", "My относится к Зои: her idea; отрицание строится без did."]),
  rsVariant("modal-must-guess", "modal-must-be-home", "Лука увидел свет в окне и сделал вывод, что его сестра дома.", "Luca: ‘My sister must be at home.’", ["Luca said that his sister must be at home.", "Luca said that his sister had to be at home.", "Luca said that his sister must to be at home.", "Luca said that my sister must be at home."], ["Must — вывод «должно быть дома», не требование находиться дома.", "Поэтому сохраняем must; my → his."]),
  rsVariant("modal-must-guess", "modal-must-be-joking", "Амира решила, что её коллеги шутят: их история показалась невероятной.", "Amira: ‘They must be joking.’", ["Amira said that they must be joking.", "Amira said that they had to joke.", "Amira said that they must to be joking.", "Amira told that they must be joking."], ["Must be joking означает вывод о происходящем; must обычно сохраняется.", "Had to joke означало бы необходимость шутить и меняло бы смысл."]),
);

REPORTED_ITEMS.push(
  rsVariant("reference-owner", "reference-phone", "Ребекка говорила о своём телефоне. Ты пересказываешь её слова.", "Rebecca: ‘My phone is new.’", ["Rebecca said that her phone was new.", "Rebecca said that my phone was new.", "Rebecca said that I phone was new.", "Rebecca said that her phone is new."], ["My относится к Ребекке, поэтому her phone.", "Is → was при backshift; I → she уже выражено в her."]),
  rsVariant("reference-owner", "reference-dog", "Нико рассказал о своей собаке, которую недавно завёл.", "Nico: ‘I walk my dog every morning.’", ["Nico said that he walked his dog every morning.", "Nico said that he walked my dog every morning.", "Nico said that I walked his dog every morning.", "Nico said that he walks his dog every morning."], ["I/my → he/his, потому что говорящий — Нико.", "Walk → walked при требуемом backshift."]),
  rsVariant("reference-you", "reference-password", "Коллега попросила тебя проверить пароль. Ты рассказываешь об этом от своего лица.", "Clara to you: ‘Your password is expired.’", ["Clara told me that my password was expired.", "Clara told me that your password was expired.", "Clara told that my password was expired.", "Clara told me that my password is expired."], ["Your из исходной фразы обозначает тебя: my в твоём пересказе.", "После told требуется адресат me; is → was."]),
  rsVariant("reference-you", "reference-you-are", "Даниэль сказал тебе, что ты готов к презентации.", "Daniel to you: ‘You are ready.’", ["Daniel told me that I was ready.", "Daniel told me that you were ready.", "Daniel told that I was ready.", "Daniel told me that I am ready."], ["You → I, потому что сказанное адресовано тебе.", "Are → was при backshift; после told стоит me."]),
  rsVariant("reference-we", "reference-project", "Люди из другого отдела сообщили о своём проекте. Ты не входишь в их группу.", "The designers: ‘We have finished our project.’", ["The designers said that they had finished their project.", "The designers said that we had finished our project.", "The designers said that they have finished their project.", "The designers said that they had finished your project."], ["We/our → they/their для внешней группы.", "Have finished → had finished: Present Perfect → Past Perfect."]),
  rsVariant("reference-we", "reference-vote", "Два друга рассказали, что приняли решение вместе. Ты пересказываешь, не будучи одним из них.", "Alex and Mina: ‘We chose our route.’", ["Alex and Mina said that they had chosen their route.", "Alex and Mina said that we had chosen our route.", "Alex and Mina said that they had chose their route.", "Alex and Mina said that they have chosen their route."], ["We/our → they/their, так как группа не включает тебя.", "Chose → had chosen: после had нужна V3 chosen."]),
  rsVariant("reference-tomorrow", "reference-next-week", "Во вторник Миа сказала, что начнёт курс в среду следующей недели. Ты пересказываешь позднее.", "Mia: ‘I will start the course next week.’", ["Mia said that she would start the course the following week.", "Mia said that she would start the course next week.", "Mia said that she will start the course the following week.", "Mia said that she would start the course the week before."], ["Will → would; I → she.", "Next week отсчитывалась от вторника: the following week сохраняет исходную точку."]),
  rsVariant("reference-tomorrow", "reference-tonight", "Утром Роб сказал, что увидится с тобой вечером. Ты пересказываешь на следующий день.", "Rob to you: ‘I will see you tonight.’", ["Rob said that he would see me that night.", "Rob said that he would see me tonight.", "Rob said that he will see me that night.", "Rob said that I would see you that night."], ["Will → would; I → he, you → me.", "Tonight исходного дня становится that night при пересказе позже."]),
  rsVariant("reference-yesterday", "reference-last-week", "В эту пятницу Ким рассказала о встрече, которая была на прошлой неделе.", "Kim: ‘I met her last week.’", ["Kim said that she had met her the week before.", "Kim said that she had met her last week.", "Kim said that she has met her the week before.", "Kim said that I had met her the week before."], ["Met → had met при backshift; I → she.", "Last week отсчитывалась от исходного разговора: the week before."]),
  rsVariant("reference-yesterday", "reference-two-days-ago", "В четверг Рахул описал визит, который был двумя днями ранее. Ты пересказываешь на следующей неделе.", "Rahul: ‘I arrived two days ago.’", ["Rahul said that he had arrived two days before.", "Rahul said that he had arrived two days ago.", "Rahul said that he has arrived two days before.", "Rahul said that I had arrived two days before."], ["Arrived → had arrived; I → he.", "Two days ago привязано к четвергу: two days before в косвенной речи."]),
  rsVariant("reference-now", "reference-this-moment", "Утром Эллиот описал своё состояние прямо тогда. Ты пересказываешь после обеда.", "Elliot: ‘I need help now.’", ["Elliot said that he needed help then.", "Elliot said that he needed help now.", "Elliot said that he needs help then.", "Elliot said that I needed help then."], ["Need → needed, I → he при backshift.", "Now в прошлом разговоре — then в твоём пересказе."]),
  rsVariant("reference-now", "reference-working-now", "Вчера Фатима сообщила, что занята именно в тот момент.", "Fatima: ‘I am working now.’", ["Fatima said that she was working then.", "Fatima said that she was working now.", "Fatima said that she is working then.", "Fatima said that I was working then."], ["Am working → was working, I → she.", "Now заменяем на then, потому что момент рассказа другой."]),
  rsVariant("reference-here", "reference-here-office", "Из дома ты пересказываешь то, что сказал Марко в офисе.", "Marco: ‘I am here in the office.’", ["Marco said that he was there in the office.", "Marco said that he was here in the office.", "Marco said that I was there in the office.", "Marco said that he is there in the office."], ["Am → was; I → he.", "Здесь исходного говорящего — there для тебя, потому что ты уже дома."]),
  rsVariant("reference-here", "reference-these-files", "После встречи ты пересказываешь слова Сэма о документах, которые были перед ним.", "Sam: ‘These files are important.’", ["Sam said that those files were important.", "Sam said that these files were important.", "Sam said that those files are important.", "Sam said that I files were important."], ["These → those при смене контекста и расстояния.", "Are → were; I не относится к files."]),
  rsVariant("reference-today", "reference-this-morning", "Вечером ты передаёшь то, что сказала Вера утром того же дня.", "Vera: ‘I am free this morning.’", ["Vera said that she was free that morning.", "Vera said that she was free this morning.", "Vera said that I was free that morning.", "Vera said that she is free that morning."], ["Am → was; I → she.", "This morning превращается в that morning, потому что исходный момент уже прошёл."]),
  rsVariant("reference-today", "reference-this-month", "В следующем месяце ты пересказываешь слова Грея о текущем для него месяце.", "Gray: ‘I am travelling this month.’", ["Gray said that he was travelling that month.", "Gray said that he was travelling this month.", "Gray said that I was travelling that month.", "Gray said that he is travelling that month."], ["Am travelling → was travelling; I → he.", "This month привязан к моменту его слов: that month в пересказе позже."]),
);

REPORTED_ITEMS.push(
  rsVariant("structure-told", "structure-told-update", "Алекс сообщил тебе, что обновление готово.", "Alex to you: ‘The update is ready.’", ["Alex told me that the update was ready.", "Alex told that the update was ready.", "Alex said me that the update was ready.", "Alex told to me that the update was ready."], ["После told в этой конструкции нужен адресат me.", "Is → was; прямое you не было частью сообщения, но адресат сохраняется после told."], "Выбери правильную конструкцию с told и backshift."),
  rsVariant("structure-told", "structure-told-call", "Соседка сообщила тебе, что позвонит позже.", "The neighbour to you: ‘I will call later.’", ["The neighbour told me that she would call later.", "The neighbour told that she would call later.", "The neighbour said me that she would call later.", "The neighbour told to me that she would call later."], ["Told + me + that + предложение: адресат обязателен.", "Will → would, I → she; to после told не ставим."]),
  rsVariant("structure-said", "structure-said-news", "Ты передаёшь новость от Фреи, но не называешь, кому она её сказала.", "Freya: ‘The train is late.’", ["Freya said that the train was late.", "Freya said me that the train was late.", "Freya told that the train was late.", "Freya said that was the train late."], ["После said адресат не нужен: said (that) + содержание.", "Is → was; в утверждении порядок the train was."]),
  rsVariant("structure-said", "structure-said-practice", "Ты сообщаешь, что сказал Джордж, без информации об адресате.", "George: ‘I practise every day.’", ["George said that he practised every day.", "George said me that he practised every day.", "George told that he practised every day.", "George said that did he practise every day."], ["Said + (that) + предложение: не said me и не told без адресата.", "I → he, practise → practised; порядок слов утверждения."]),
  rsVariant("structure-said-to", "structure-said-to-bus", "Эмма сказала это тебе. Условие требует сохранить said и назвать тебя.", "Emma to you: ‘The bus is here.’", ["Emma said to me that the bus was there.", "Emma said me that the bus was there.", "Emma said to me that the bus is there.", "Emma said to me that I was there."], ["С адресатом say строится как said to me, не said me.", "Is → was; here → there, потому что ты пересказываешь позже в другом месте."], "Сохрани said, укажи адресата и используй backshift."),
  rsVariant("structure-said-to", "structure-said-to-lunch", "Джеймс сказал это тебе, и ты передаёшь его слова с said.", "James to you: ‘I am making lunch.’", ["James said to me that he was making lunch.", "James said me that he was making lunch.", "James said to me that I was making lunch.", "James said to me that he is making lunch."], ["Say требует to перед адресатом: said to me.", "I → he; am making → was making."]),
  rsVariant("structure-that", "structure-that-busy", "Рэй сказал: «Я занят». Начни с Ray said и опусти that.", "Ray: ‘I am busy.’", ["Ray said he was busy.", "Ray said was he busy.", "Ray told he was busy.", "Ray said he busy."], ["That опционально: Ray said he was busy.", "I → he, am → was; порядок слов остаётся как в утверждении."], "Передай с backshift без that."),
  rsVariant("structure-that", "structure-that-expect", "Мила сказала: «Я ожидаю письмо». Начни с Mila said и не используй that.", "Mila: ‘I expect an email.’", ["Mila said she expected an email.", "Mila said did she expect an email.", "Mila told she expected an email.", "Mila said she expect an email."], ["That можно убрать после said.", "Expect → expected; I → she. В косвенном утверждении нет did."], "Передай с backshift без that."),
  rsVariant("structure-says", "structure-says-bilbao", "Сэм говорит это сейчас о своей текущей жизни. Сохрани настоящее.", "Sam: ‘I live in Bilbao.’", ["Sam says that he lives in Bilbao.", "Sam says that he lived in Bilbao.", "Sam says that I live in Bilbao.", "Sam says me that he lives in Bilbao."], ["После says настоящее сохраняем для текущего факта.", "I → he; he lives требует -s, это согласование лица, не backshift."], "Начни с Sam says и сохрани настоящее время."),
  rsVariant("structure-says", "structure-says-need", "Менеджер говорит это прямо сейчас о своей потребности.", "The manager: ‘I need more time.’", ["The manager says that she needs more time.", "The manager says that she needed more time.", "The manager says that I need more time.", "The manager says me that she needs more time."], ["Says — настоящее время глагола сообщения, поэтому need остаётся настоящим.", "I → she; needs согласуется с she."]),
  rsVariant("structure-still-true", "structure-still-true-job", "Вчера Педро сказал, что работает в этой компании, и сегодня это всё ещё факт. Подчеркни актуальность.", "Pedro: ‘I work for this company.’", ["Pedro said that he works for this company.", "Pedro said that he had worked for this company.", "Pedro said that I work for this company.", "Pedro told that he works for this company."], ["Факт всё ещё верен, поэтому в этом задании сохраняем Present Simple works.", "I → he; lived/works выбираем по актуальности, здесь нужна works."], "Сохрани настоящее время для по-прежнему верного факта."),
  rsVariant("structure-still-true", "structure-still-true-health", "Недавно Ида сказала, что не ест мясо; её привычка не изменилась. Сохрани настоящее.", "Ida: ‘I don't eat meat.’", ["Ida said that she doesn't eat meat.", "Ida said that she hadn't eaten meat.", "Ida said that I don't eat meat.", "Ida told that she doesn't eat meat."], ["Настоящее doesn't подчёркивает сохраняющуюся привычку.", "I → she; doesn't eat — обычная форма Present Simple для she."], "Сохрани настоящее время для по-прежнему верного факта."),
  rsVariant("structure-general-truth", "structure-general-truth-water", "Учитель сообщил общеизвестный научный факт. Оставь его в настоящем.", "The teacher: ‘Water boils at 100°C.’", ["The teacher said that water boils at 100°C.", "The teacher said that water boiled at 100°C.", "The teacher told that water boils at 100°C.", "The teacher said that does water boil at 100°C."], ["Общую истину можно передать в Present Simple: water boils.", "После said обычный порядок слов, без does."]),
  rsVariant("structure-general-truth", "structure-general-truth-sun", "Гид сообщил факт о восходе солнца. Сохрани его как общее знание.", "The guide: ‘The sun rises in the east.’", ["The guide said that the sun rises in the east.", "The guide said that the sun rise in the east.", "The guide told that the sun rises in the east.", "The guide said that does the sun rise in the east."], ["Общий факт остаётся в настоящем: the sun rises.", "Rises согласуется с sun; в косвенном утверждении нет does."]),
  rsVariant("structure-same-context", "structure-same-context-now", "Адам только что сказал это рядом с тобой. Вы всё ещё ждёте тот же автобус в том же месте.", "Adam: ‘I am waiting here now.’", ["Adam said that he is waiting here now.", "Adam said that I am waiting here now.", "Adam told that he is waiting here now.", "Adam said he waiting here now."], ["По условию место и момент не изменились, поэтому is waiting / here / now остаются.", "I → he; форма is waiting требует помощник is."], "Сохрани актуальное время, место и момент без backshift."),
  rsVariant("structure-same-context", "structure-same-context-today", "София только что сообщила новость в том же офисе и в тот же день. Факт всё ещё актуален.", "Sofia: ‘I am free today.’", ["Sofia said that she is free today.", "Sofia said that I am free today.", "Sofia told that she is free today.", "Sofia said she free today."], ["Тот же день и актуальный факт: is free / today сохраняются.", "I → she; после said не нужен адресат."]),
);

const REPORTED_TENSE_ROWS = [
  ["Present Simple", "Past Simple", "work → worked · am/is → was · are → were"],
  ["Present Continuous", "Past Continuous", "am working → was working"],
  ["Past Simple", "Past Perfect", "sent → had sent"],
  ["Present Perfect", "Past Perfect", "have sent → had sent"],
  ["Past Continuous", "Past Perfect Continuous", "was working → had been working"],
  ["Present Perfect Continuous", "Past Perfect Continuous", "have been working → had been working"],
  ["Past Perfect / Past Perfect Continuous", "без дальнейшего сдвига", "had sent → had sent · had been working → had been working"],
  ["will", "would", "will help → would help"],
  ["can", "could", "can stay → could stay"],
  ["may (возможность)", "might", "may arrive → might arrive"],
  ["must (обязанность)", "обычно had to", "must leave → had to leave"],
  ["could / should / might / would", "обычно без изменений", "should rest → should rest"],
];

function rsEscape(value) {
  return String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
}

function reportedQuestionFor(item, recognizeRule = false) {
  const correctAnswer = recognizeRule ? item.rule : item.answers[0];
  // Don't pit a broad rule against its equally valid special case.
  const overlapping = [
    ["tense-work", "tense-be", "tense-negative"],
    ["structure-says", "structure-still-true", "structure-general-truth"],
  ].find(ids => ids.includes(item.ruleKey)) || [item.ruleKey];
  const rulePool = REPORTED_ITEMS.filter(entry => entry.group === item.group && !overlapping.includes(entry.ruleKey))
    .filter((entry, index, entries) => entries.findIndex(other => other.ruleKey === entry.ruleKey) === index);
  const focus = {
    "structure-told": "Почему после told стоит me?",
    "structure-said": "Как вводится содержание после said без адресата?",
    "structure-said-to": "Почему между said и me стоит to?",
    "structure-that": "Почему после said можно сразу поставить he?",
    "structure-says": "Почему после says стоит настоящее works?",
    "structure-still-true": "Почему после said сохранилось настоящее lives?",
    "structure-general-truth": "Почему сохранилось настоящее orbits?",
    "structure-same-context": "Почему сохранились here и today?",
  }[item.id] || ({ tense: "Как изменена форма основного глагола?", modal: "Что произошло с модальной конструкцией?", reference: "Как изменились местоимения или слова времени/места?" }[item.group]);
  const candidates = recognizeRule
    ? [item.rule, ...shuffle(rulePool.map(entry => entry.rule)).slice(0, 3)]
    : item.answers;
  const answers = shuffle(candidates);
  return {
    id: item.id, type: recognizeRule ? "reported-rule" : "reported", topicKey: "reportedSpeech",
    context: `${item.context} ${recognizeRule ? focus : item.instruction}`,
    text: recognizeRule ? `${rsEscape(item.direct)}<br><span class="reported-result">→ ${rsEscape(item.answers[0])}</span>` : rsEscape(item.direct),
    answers, correct: answers.indexOf(correctAnswer), example: item.answers[0],
    explanation: `<b>${rsEscape(item.rule)}</b><ul class="reported-changes">${item.changes.map(change => `<li>${rsEscape(change)}</li>`).join("")}</ul>`,
  };
}

function startReportedSession() {
  // Three different examples per group: two transformations and one rule question.
  const questions = ["tense", "modal", "reference", "structure"].flatMap(group =>
    shuffle(REPORTED_ITEMS.filter(item => item.group === group)).slice(0, 3)
      .map((item, index) => reportedQuestionFor(item, index === 2))
  );
  startSession("reported-speech", "Косвенная речь", shuffle(questions));
}

function renderReportedGuide() {
  guide.innerHTML = `
    <button class="back-button" type="button" data-action="home">← К каталогу</button>
    <article class="lesson-card guide-page reported-guide">
      <span class="lesson-tag">Reported statements</span>
      <h1>Как передать чужие слова</h1>
      <p class="subtitle">Не переводим «слово в слово»: проверяем время, участников разговора и точку отсчёта.</p>
      <div class="lesson-actions"><button class="primary-button" type="button" data-action="start-reported">Начать 12 заданий</button></div>
      <div class="reported-example"><strong>Marta: “I am working.”</strong><span>→ Marta said (that) she was working.</span><p>I → she: говорим о Марте. Am working → was working: переносим процесс в прошлое.</p></div>
      <ol class="reported-steps"><li><b>Кто и когда сказал?</b> Says и said задают разную точку отсчёта.</li><li><b>Нужен ли backshift?</b> При пересказе прошлого обычно сдвигаем время назад.</li><li><b>Кто такие I, you, we?</b> Меняем по участникам, а не по слепой таблице.</li><li><b>Те же место и день?</b> Меняем here/today только если они больше не точны.</li></ol>
      <h2 class="guide-heading">Таблица сдвига времён</h2>
      <p>Это схема стандартного backshift после said/told, а не запрет на другие варианты при живом общении.</p>
      <div class="reported-table-wrap" role="region" aria-label="Сдвиг времён" tabindex="0"><table class="reported-table"><thead><tr><th scope="col">Было</th><th scope="col">Стало</th><th scope="col">Форма</th></tr></thead><tbody>${REPORTED_TENSE_ROWS.map(row => `<tr>${row.map(cell => `<td>${rsEscape(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>
      <aside class="principle-box"><b>Не все must одинаковы:</b> обязанность обычно передаём через had to; must в значении вывода («должно быть») обычно сохраняем. May о возможности → might; разрешение с may часто передаём через could.</aside>
      <details class="reported-details" open><summary>Said, told и необязательное that</summary><div class="aux-chain-list"><div><strong>She said (that) she was ready.</strong><span>Адресат не обязателен.</span></div><div><strong>She told me (that) she was ready.</strong><span>При пересказе утверждения после told называем адресата: me, us, Anna.</span></div><div><strong>She said to me that she was ready.</strong><span>С said адресат вводится через to. Said me — ошибка, said to me — правильно.</span></div></div><p>That можно убрать. После него обычный порядок слов: <b>she was</b>, не <b>was she</b>.</p></details>
      <details class="reported-details"><summary>Местоимения: кто говорит и кому?</summary><p>Tom to you: “I will help you.” → Tom said that <b>he</b> would help <b>me</b>. I — Том, you — ты, пересказывающий от своего лица.</p><p>Если пересказываешь собственные слова: I said I was tired. I остаётся I. We сохраняется, если ты всё ещё говоришь от лица той же группы.</p></details>
      <details class="reported-details"><summary>День и место: tomorrow, yesterday, here…</summary><div class="reported-reference-grid"><span>now → then</span><span>today → that day</span><span>tomorrow → the next / following day</span><span>yesterday → the day before / previous day</span><span>here → there</span><span>this / these → that / those</span><span>last week → the week before</span><span>next week → the following week</span><span>two days ago → two days before</span></div><p>В понедельник “tomorrow” означает вторник. В пересказе в среду — “the next day” после понедельника, а не после среды. В том же месте и в тот же день here и today можно сохранить.</p></details>
      <details class="reported-details"><summary>Когда можно не сдвигать время?</summary><p>После says для текущего факта: She says she works remotely. После said настоящее тоже возможно, если факт всё ещё верен, общеизвестен или ты передаёшь ещё актуальную новость.</p><p>Сдвинутый вариант часто также допустим. Поэтому в упражнениях явно указано: нужен backshift или требуется сохранить актуальное настоящее. Само по себе «сказано недавно» не отменяет согласование автоматически.</p></details>
      <h2 class="guide-heading">Практика: пересказ + определение правила</h2><p>${REPORTED_ITEMS.length} контекстных примеров. В подходе — 8 заданий на пересказ и 4 на правило; время, модальные, местоимения и конструкция said/told встречаются каждый раз.</p>
      <div class="lesson-actions"><button class="primary-button" type="button" data-action="start-reported">Начать 12 заданий</button><button class="secondary-button" type="button" data-action="home">К каталогу</button></div>
      <p class="reported-sources">Проверить правила: <a href="https://learnenglish.britishcouncil.org/free-resources/grammar/b1-b2/reported-speech-statements" target="_blank" rel="noopener noreferrer">British Council</a> · <a href="https://dictionary.cambridge.org/grammar/british-grammar/reported-speech-indirect-speech" target="_blank" rel="noopener noreferrer">Cambridge Grammar</a>.</p>
    </article>`;
  showOnly(guide);
}\n
